/**
 * Coercion of STAC Collection JSON into the app's own card vocabulary.
 *
 * PURE AND ENGINE-FREE: no fetch, no DOM, no store. Everything here is a
 * function of `unknown` — the input is a third party's JSON, so nothing is
 * assumed about its types, only tested.
 *
 * WHY SO MUCH COERCION. The Open3D City catalog is generated by several
 * pipelines of different vintages, so the same summary key arrives in several
 * shapes: `city3d:lods` is `["0","1.2"]` in most collections, bare numbers
 * `[2]` in the degraded ones, and carries non-numeric values like PLATEAU's
 * `"T"`; `city3d:city_objects` is sometimes a `{min,max,total}` stats object
 * and sometimes a plain count; a spatial bbox is 4 numbers or 6 (with z), and
 * a handful of collections never reprojected theirs, so Zurich's "longitude"
 * is 2.6 million EPSG:2056 metres. Normalising once, here, keeps every
 * consumer from re-deciding what a value means — and keeps a bogus bbox from
 * reaching the camera, which would fly to a point that does not exist.
 */

import type { StacCollectionCard } from "./stacTypes";

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** A summary leaf we can show as text, or null if it is not one. */
function scalarToString(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (typeof value === "number")
    return Number.isFinite(value) ? String(value) : null;
  if (typeof value === "boolean") return String(value);
  return null;
}

/**
 * A summary value as a list of display strings.
 *
 * Arrays are flattened one level (a JSON Schema-ish summary occasionally nests
 * one), scalars are wrapped, numbers and booleans are stringified, and objects
 * / null / undefined / non-finite numbers are dropped rather than rendered as
 * "[object Object]". The result is deduped with first-seen order preserved, so
 * an LoD list stays in the catalog's own order.
 */
export function flattenSummary(value: unknown): readonly string[] {
  const out: string[] = [];
  const seen = new Set<string>();

  const visit = (node: unknown, depth: number): void => {
    if (Array.isArray(node)) {
      // depth 0 = the summary itself, 1 = one level of nesting. Deeper arrays
      // are not a shape this catalog has, and flattening them blindly would
      // turn a stats structure into noise.
      if (depth >= 2) return;
      for (const child of node) visit(child, depth + 1);
      return;
    }
    const text = scalarToString(node);
    if (text === null || seen.has(text)) return;
    seen.add(text);
    out.push(text);
  };

  visit(value, 0);
  return out;
}

/**
 * A boolean summary, where a one-element array is the catalog's usual way of
 * saying "every item agrees".
 *
 * `[false]` is `false` — a real answer meaning "no textures anywhere" — while a
 * mixed `[true, false]`, an absent key or a non-boolean is `null`, "unknown".
 * A card must be able to render those three cases differently.
 */
export function summaryBoolean(value: unknown): boolean | null {
  const unwrapped = Array.isArray(value)
    ? value.length === 1
      ? value[0]
      : undefined
    : value;
  return typeof unwrapped === "boolean" ? unwrapped : null;
}

/** `{min,max,total}` → total, a bare count → itself, anything else → null. */
export function cityObjectsTotal(value: unknown): number | null {
  if (typeof value === "number") return Number.isFinite(value) ? value : null;
  if (isRecord(value)) {
    const total = value.total;
    if (typeof total === "number" && Number.isFinite(total)) return total;
  }
  return null;
}

/**
 * A bounding box that is genuinely WGS84 degrees, or null.
 *
 * Rejects non-finite numbers, out-of-range degrees (which is how a bbox left
 * in projected metres announces itself) and non-increasing edges (inverted or
 * zero-area). A null here means "do not offer to fly to this", not "hide it".
 */
export function validBbox2d(
  minLng: number,
  minLat: number,
  maxLng: number,
  maxLat: number,
): readonly [number, number, number, number] | null {
  const all = [minLng, minLat, maxLng, maxLat];
  if (!all.every((n) => typeof n === "number" && Number.isFinite(n)))
    return null;
  if (minLng < -180 || maxLng > 180) return null;
  if (minLat < -90 || maxLat > 90) return null;
  if (minLng >= maxLng || minLat >= maxLat) return null;
  return [minLng, minLat, maxLng, maxLat];
}

/**
 * The first spatial extent of a Collection as a validated 2D box.
 *
 * STAC allows a 6-element bbox (`[minX,minY,minZ,maxX,maxY,maxZ]`); its z
 * values are frequently sentinel garbage such as `-2147483.75`, so only the
 * horizontal indices `[0,1,3,4]` are read and the z values are ignored
 * outright.
 */
export function extent2dFromCollection(
  collection: unknown,
): readonly [number, number, number, number] | null {
  if (!isRecord(collection)) return null;
  const spatial = isRecord(collection.extent)
    ? collection.extent.spatial
    : null;
  const bboxes = isRecord(spatial) ? spatial.bbox : null;
  if (!Array.isArray(bboxes)) return null;
  const first = bboxes[0];
  if (!Array.isArray(first)) return null;

  const indices =
    first.length === 6
      ? [0, 1, 3, 4]
      : first.length === 4
        ? [0, 1, 2, 3]
        : null;
  if (indices === null) return null;

  const [minLng, minLat, maxLng, maxLat] = indices.map(
    (i): unknown => first[i],
  );
  if (
    typeof minLng !== "number" ||
    typeof minLat !== "number" ||
    typeof maxLng !== "number" ||
    typeof maxLat !== "number"
  ) {
    return null;
  }
  return validBbox2d(minLng, minLat, maxLng, maxLat);
}

/** The media type of the stac-geoparquet items mirror. */
const PARQUET_MEDIA_TYPE = "application/vnd.apache.parquet";
/** The role the catalog tags that mirror with. */
const PARQUET_ROLE = "collection-mirror";

/**
 * The absolute href of a collection's items parquet mirror, or null.
 *
 * Matched by media type OR role rather than by asset key: the key is
 * `items-geoparquet` in most collections but not all, and only about 22 of 53
 * collections have a mirror at all, so "not found" is an ordinary outcome.
 */
function itemsParquetHrefFrom(
  assets: unknown,
  collectionHref: string,
): string | null {
  if (!isRecord(assets)) return null;
  for (const asset of Object.values(assets)) {
    if (!isRecord(asset)) continue;
    const roles = Array.isArray(asset.roles) ? asset.roles : [];
    const matches =
      asset.type === PARQUET_MEDIA_TYPE || roles.includes(PARQUET_ROLE);
    if (!matches || typeof asset.href !== "string") continue;
    try {
      return new URL(asset.href, collectionHref).href;
    } catch {
      return null;
    }
  }
  return null;
}

function firstOrNull(values: readonly string[]): string | null {
  return values[0] ?? null;
}

/**
 * A browsable card from a fetched `collection.json`.
 *
 * Returns null when the JSON is not a usable Collection — an `id` is the one
 * field with no sensible fallback, since it is what every later fetch (items,
 * parquet, share link) is keyed by. `type: "Collection"` is deliberately NOT
 * required: some of the catalog's older shells omit it, and rejecting them
 * would silently shrink the browser.
 */
export function collectionCardFromJson(
  json: unknown,
  collectionHref: string,
): StacCollectionCard | null {
  if (!isRecord(json) || typeof json.id !== "string" || json.id === "") {
    return null;
  }

  const summaries = isRecord(json.summaries) ? json.summaries : {};

  return {
    id: json.id,
    title:
      typeof json.title === "string" && json.title !== ""
        ? json.title
        : json.id,
    description: typeof json.description === "string" ? json.description : "",
    license: typeof json.license === "string" ? json.license : null,
    extent2d: extent2dFromCollection(json),
    lods: flattenSummary(summaries["city3d:lods"]),
    coTypes: flattenSummary(summaries["city3d:co_types"]),
    version: firstOrNull(flattenSummary(summaries["city3d:version"])),
    projCodes: flattenSummary(summaries["proj:code"]),
    semanticSurfaces: summaryBoolean(summaries["city3d:semantic_surfaces"]),
    textures: summaryBoolean(summaries["city3d:textures"]),
    materials: summaryBoolean(summaries["city3d:materials"]),
    cityObjectsTotal: cityObjectsTotal(summaries["city3d:city_objects"]),
    itemsParquetHref: itemsParquetHrefFrom(json.assets, collectionHref),
    collectionHref,
  };
}
