/**
 * The Open3D City STAC catalog, fetched.
 *
 * ENGINE-FREE and store-free, like `features/geocode/photon.ts`: a function of
 * an `AbortSignal` returning plain data, so it is unit-testable against a
 * mocked `fetch` and callable from a hook, a test or a script alike. Coercion
 * of a collection's JSON into a card is NOT done here — that is
 * `stacNormalize.collectionCardFromJson`, which is pure and tested on its own.
 *
 * WHY A CRAWL AND NOT ONE REQUEST. A STAC root catalog is a link document: it
 * lists ~53 `rel:"child"` hrefs and carries none of the metadata a card shows,
 * so the browser genuinely needs one request per collection. That is why the
 * fan-out is BOUNDED — an unthrottled `Promise.all` over every child opens
 * fifty-odd sockets at once, which the browser then serialises anyway (HTTP/1.1
 * caps at ~6 per origin) while burning memory and making cancellation useless.
 *
 * WHY ONE BAD COLLECTION IS NOT AN ERROR. The catalog is generated by several
 * pipelines and a few of its shells are broken or half-published. A single 404
 * emptying the browser would be a worse failure than quietly showing 52 of 53,
 * so per-collection failures are logged and skipped; only an unreachable ROOT
 * is fatal, because then there is nothing to show at all.
 */

import { collectionCardFromJson } from "./stacNormalize";
import type { StacCollectionCard } from "./stacTypes";

/**
 * The published catalog root.
 *
 * HARDCODED ON PURPOSE — no `VITE_` override. A build-time env var here would
 * invite the same dotenvx-ciphertext footgun the Maps key has (a `.env` shipped
 * encrypted leaks an unusable string into the bundle), and this URL is a public
 * static file with no secret and no per-deployment variation to justify it.
 */
export const STAC_CATALOG_URL =
  "https://storage.googleapis.com/city3d-stac/catalog.json";

/**
 * How many collection requests may be in flight at once.
 *
 * Six matches a browser's own per-origin connection limit on HTTP/1.1: going
 * higher does not make the crawl faster, it only queues inside the browser
 * where this code can no longer see or cancel it.
 */
export const COLLECTION_FETCH_CONCURRENCY = 6;

/** A link entry of a STAC catalog, typed as loosely as it arrives. */
interface StacLink {
  readonly href?: unknown;
  readonly rel?: unknown;
}

/** True for a DOM/undici abort rejection, which must never be swallowed. */
function isAbortError(error: unknown): boolean {
  return error instanceof Error && error.name === "AbortError";
}

/** Fetch and parse JSON, rejecting a non-ok response. */
async function fetchJson(url: string, signal?: AbortSignal): Promise<unknown> {
  const response = await fetch(url, { signal });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  return (await response.json()) as unknown;
}

/** The unreachable-root message, in one place so tests and UI agree. */
function rootFailure(detail: string, cause?: unknown): Error {
  return new Error(`Could not reach the 3D city catalog${detail}.`, { cause });
}

/**
 * The absolute hrefs of a root catalog's child collections.
 *
 * Hrefs in this catalog are relative (`./aaa/collection.json`) and MUST be
 * resolved against the catalog's own URL, not merely concatenated — a
 * non-resolving join would request a path that does not exist. Anything that
 * fails to resolve (a malformed href) is dropped rather than thrown on.
 */
function childHrefs(catalog: unknown, catalogUrl: string): string[] {
  const links = (catalog as { links?: unknown })?.links;
  if (!Array.isArray(links)) return [];

  const hrefs: string[] = [];
  const seen = new Set<string>();
  for (const link of links as StacLink[]) {
    if (link?.rel !== "child" || typeof link.href !== "string") continue;
    let resolved: string;
    try {
      resolved = new URL(link.href, catalogUrl).href;
    } catch {
      continue;
    }
    if (seen.has(resolved)) continue;
    seen.add(resolved);
    hrefs.push(resolved);
  }
  return hrefs;
}

/**
 * Every collection of the catalog, as cards sorted by title.
 *
 * REJECTS only when the root is unreachable, or when `signal` aborts — an
 * `AbortError` is re-thrown unwrapped so a caller can tell "the user moved on"
 * apart from "the catalog is down". Individual collections that fail, or whose
 * JSON is not a usable Collection, are warned about once each and omitted.
 */
export async function fetchStacCollections(
  signal?: AbortSignal,
): Promise<StacCollectionCard[]> {
  const response = await fetch(STAC_CATALOG_URL, { signal }).catch(
    (error: unknown) => {
      if (isAbortError(error)) throw error;
      // A network failure or a CORS rejection: the user needs an actionable
      // sentence, not the browser's bare "Failed to fetch".
      throw rootFailure("", error);
    },
  );
  if (!response.ok) throw rootFailure(` (HTTP ${response.status})`);

  const catalog = await (response.json() as Promise<unknown>).catch(
    (error: unknown) => {
      // The body is still streaming here, so an abort lands on THIS read just
      // as easily as on the request above — and wrapping it would tell the
      // user the catalog is broken when they simply navigated away.
      if (isAbortError(error)) throw error;
      throw rootFailure(" (its response was not valid JSON)", error);
    },
  );

  const hrefs = childHrefs(catalog, STAC_CATALOG_URL);
  const cards: StacCollectionCard[] = [];

  // A shared cursor consumed by a fixed pool of workers: each worker takes the
  // next index and awaits its own request, so exactly
  // COLLECTION_FETCH_CONCURRENCY requests are ever open, and the pool drains
  // as fast as the fastest responses allow (unlike fixed-size batching, which
  // would stall a whole batch on its slowest member).
  let cursor = 0;
  const worker = async (): Promise<void> => {
    for (;;) {
      const index = cursor++;
      const href = hrefs[index];
      if (href === undefined) return;
      try {
        const json = await fetchJson(href, signal);
        const card = collectionCardFromJson(json, href);
        if (card !== null) cards.push(card);
        else console.warn("STAC collection skipped:", href, "not a Collection");
      } catch (error) {
        if (isAbortError(error)) throw error;
        console.warn("STAC collection skipped:", href, error);
      }
    }
  };

  await Promise.all(
    Array.from(
      { length: Math.min(COLLECTION_FETCH_CONCURRENCY, hrefs.length) },
      worker,
    ),
  );

  // Sorted here rather than in the UI so every consumer (list, share link,
  // tests) sees the same order regardless of which response won the race. The
  // id breaks ties, because two collections CAN share a title and a race-order
  // fallback would reshuffle the list between loads.
  return cards.sort(
    (a, b) => a.title.localeCompare(b.title) || a.id.localeCompare(b.id),
  );
}
